### PR TITLE
Add support for Django 2

### PR DESCRIPTION
**Pull request by jayvdb**
Added urls.py for stores and dashboard, and updated README.rst
to explain how to use stores with Django 1 and 2.

Closes https://github.com/django-oscar/django-oscar-stores/issues/120

### CODE REVIEW

**Comment by jayvdb** [comment]
This duplicates the `get_urls()`, as I couldnt get that to work.  Happy to make further changes to improve this.

**Comment by solarissmoke** [comment]
Hey @jayvdb thanks for this. I'm not convinced there is an issue here however. The package already works with Django 2 (we're running it in production with 2.2), using the existing URL configs, which don't need to be duplicated.

The sandbox that is included in this repo works with Django 2, so the existing URL configuration is fine. Have you tried running this sandbox? 

If that works, but your project doesn't, then it would suggest the issue is with how your project is set up. I would compare the sandbox configuration to your own to see if there are any obvious differences. If you can't find any perhaps post your configuration on the Oscar mailing list?

**Comment by jayvdb** [comment]
I'll try running the sandbox.
I notice the sandbox also adds `'stores.dashboard'` to the installed apps, which isnt mentioned on the README, and is likely the cause of at least one of the problems I encountered in https://github.com/django-oscar/django-oscar-stores/issues/120.

**Comment by jayvdb** [comment]
Adding `'stores.dashboard'` to the installed apps appears to have fixed things for me.  I'll send in another PR to fix that, after a bit more verification.

**Comment by solarissmoke** [comment]
Cool. Please also include the fix to the geoip link in the PR.

**Pull request closed without merging**
